import { Geist, Geist_Mono, Inter, Playfair, Sacramento } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sacramento = Sacramento({
    variable: "--font-sacramento",
    subsets: ['latin','latin-ext'],
    weight: ['400']
})

const playfair = Playfair({
    variable: "--font-playfair",
    subsets: ['cyrillic', 'cyrillic-ext', 'latin','latin-ext','vietnamese'],
})

const inter = Inter({
    variable: '--font-inter',
    subsets: ['cyrillic', 'cyrillic-ext', 'greek', 'greek-ext', 'latin', 'latin-ext']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${sacramento.variable} ${playfair.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
